vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        plugin_images:
            uri_prefix: /images/plugins
            upload_destination: '%kernel.project_dir%/public/images/plugins'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer